from turtle import *
color("red")
begin_fill()
pensize(30)
# setposition(0, 0)
left(50)
forward(133)
circle(50, 200)
right(140)
circle(50, 200)
forward(133)
end_fill()
# penup()
# setposition(0, 220)
# pendown()
# write("Love from Deecode", font=("Arial",18,"norml"), align="center")
# hideturtle()
# done()
